name: protoc

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  protoc:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # This should be captured by script later
      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
      - name: Docker Login to GHCR
        id: docker_login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository_owner }} ghcr.io --password-stdin

      # Pull the image and generate for golang and dart
      - name: Pull, Lint, and Generate
        id: pull_protoc
        run : |
          ./cicd.sh -arlgd

      # Auto Commit
      # https://github.com/stefanzweifel/git-auto-commit-action
      - name: Auto Commit
        id: auto_commit
        if: github.ref != 'refs/heads/main'
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Automated Change

      # Bump Version
      # https://github.com/remorses/bump-version
      - name: Bump versions
        id: bum_version
        if: github.ref != 'refs/heads/main'
        uses: remorses/bump-version@js
        with:
            version_file: ./version.txt
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

