name: protoc

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  protoc:
    runs-on: ubuntu-latest
    permissions:
      packages: read
      contents: write
    steps:

      # Checkout
      - name: Checkout repository
        uses: actions/checkout@v2

      # This should be captured by script later
      # https://docs.github.com/en/packages/working-with-a-github-packages-registry/working-with-the-container-registry
      - name: Docker Login to GHCR
        id: docker_login
        run: |
          echo ${{ secrets.GITHUB_TOKEN }} | docker login -u ${{ github.repository_owner }} ghcr.io --password-stdin

      # Pull the image and generate for golang and dart
      - name: Pull and Generate
        id: pull_protoc
        run : |
          ./cicd.sh -argd

      # # Auto Commit
      # # https://github.com/stefanzweifel/git-auto-commit-action
      # - name: Auto Commit
      #   id: auto_commit
      #   uses: stefanzweifel/git-auto-commit-action@v4
      #   with:
      #     commit_message: Automated Change

      - name: Bump versions
        uses: remorses/bump-version@js
        with:
            version_file: ./version.txt
        env:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # # Bump the version and tag it 
      # # https://github.com/marketplace/actions/github-tag
      # # Switch: https://github.com/marketplace/actions/bump-versions
      # - name: Bump Version
      #   id: bump_version
      #   uses: mathieudutour/github-tag-action@v6.0
      #   with:
      #     github_token: ${{ secrets.GITHUB_TOKEN }}

      # # Create a release
      # # https://github.com/ncipollo/release-action
      # # TODO: Tar the target libs prior as artifacts for release. Whole repo is fine for now.
      # - name: Release
      #   id: release
      #   uses: ncipollo/release-action@v1
      #   with:
      #     tag: ${{ steps.bump_version.outputs.new_tag }}
      #     name: Release ${{ steps.bump_version.outputs.new_tag }}
      #     body: ${{ steps.bump_version.outputs.changelog }}
      #     generateReleaseNotes: true

